### ISSUE TITLE
Limit container resources

### ISSUE THREAD

**Issue by carlosms** [src-d/sourced-ce#91]
This issue is to find a way to limit the containers resources so they don't freeze the host.
Ideally this can be done with settings in the compose file.

Otherwise gitcollector `v0.0.1-beta.6` already supports `GITCOLLECTOR_HALF_CPU=true`, other containers may have similar confs.

**Comment by carlosms** [comment]
related #96

**Comment by smacker** [comment]
https://nickjanetakis.com/blog/docker-tip-78-using-compatibility-mode-to-set-memory-and-cpu-limits

Limits can be set like this:
```yaml
services:
  redis:
    image: "redis:alpine"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "50M"
```

but docker-compose has to be run with `--compatibility` flag.
